---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Data science on a chromebook

The goal of this meetup is to show that you can work from a cheap chromebook.

It's inspired by the post [Data Science on a
Chromebook](https://simplystatistics.org/posts/2017-08-29-data-science-on-a-chromebook/)
(Jeff Leek, 2017) and by my urgent need for a computer when my main one broke
down.

**Who is the audience?**

Data scientists, including analysts and software developers.

**Why is this important?**

This meetup is particularly useful if you lack a powerful computer at hand. It
can save you from buying a computer more expensive than you need.

**Objectives**

* Overview of my chromebook.
* Use an online computer with "unlimited" resources.
* Use an offline computer with limited resources.

## Overview of my chromebook

* Cost: USD 120.
* Resources: 2 cores, 4GB memory, 64GB storage.
* ChromeOS:
    * Few apps.
    * Lean keyboard (e.g. lacks CAPS lock, right-click, del) ([simulator](https://partnerdash.google.com/apps/simulator/chromebook#get-to-know-your-keyboard?l=en)).
    * Files: Local (MyFiles) and remote (Google Drive).

## Use an online computer with "unlimited" resources

* Example computer running RStudio on the cloud.
* [How to setup a computer on the cloud](https://youtu.be/_pBqBfjTKI4).
* [How to scale your computing resources up and down](https://youtu.be/NF7HPKt55Yk).

## Use an offline computer with limited resources

* [Setup a Linux development environment](https://chromeos.dev/en/linux/setup).
* [Sharing files to Linux](https://chromeos.dev/en/linux/setup#sharing-files-to-linux).
* [Install Docker engine](https://docs.docker.com/engine/install/) ([ds.docker](https://github.com/2degreesInvesting/ds.docker)).
* Use software via docker, e.g. RStudio via the [rocker/verse](https://rocker-project.org/images/versioned/rstudio.html) image.

Personalize:

* Setup SSH keys to for GitHub. I [install `gh`](https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt) then run `gh auth login`.
* Configure git. I install my .gitconfig along with other [dotfiles](https://github.com/maurolepore/dotfiles) ([watch](https://youtu.be/BYtt2cXW4qg)).
* I also use [oh-my-zsh](https://ohmyz.sh/#install) and a few other programs.

## Takeaway

* You can do data science on a cheap chromebook.
* The limitations are relatively few -- mainly when working offline.
